spring:
  datasource:
    username: root
    url: jdbc:mysql://root:12345678@localhost:3306/myshoes
    password: '12345678'
cloudinary:
  cloud_name: dwgusqbpa
  api_key: '476734569334626'
  api_secret: 5CKGbSals-qC1lRiu7wPwr6fC7o

auth:
  jwt:
    secret: dtienanh1909
    refresh-expiration: 600000
    token-expiration: 600000
  public-end-points:
    - /auth
vnpay:
  tmn-code: O9IG86PT
  hash-secret: CXXMBGVOQGKJVRWIWX7S91HWCDM3X6DK
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  version: 2.1.0
  command: pay
  order-type: other
  return-url: http://localhost:8080/payment/vnpay-callback
  expiration-time: 300000

app:
  module-auth: /auth