spring:
  datasource:
    username: root
    url: jdbc:mysql://root:12345678@localhost:3306/module-auth
    password: '12345678'
jwt:
  secret: dtienanh1909
  token-expiration: 600000
  refresh-expiration: 1200000
